# Generated by Django 3.2.13 on 2022-07-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teachers', '0001_initial'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_category', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPublishQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.classes')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.questionbank')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未提交'), (1, '结果不正确'), (2, '结果正确')], default=0)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.questionbank')),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_Detail', models.CharField(max_length=1024)),
                ('total_students_finish', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.questioncategory')),
            ],
        ),
        migrations.AddField(
            model_name='questionbank',
            name='desc_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Questions.questionbankdesc'),
        ),
    ]
