# Generated by Django 3.2.13 on 2022-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_rename_desc_id_questionbank_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankdesc',
            name='ques_answer',
            field=models.CharField(default='123/123/213', max_length=1024, unique=True),
        ),
        migrations.AddField(
            model_name='questionbankdesc',
            name='ques_sample',
            field=models.CharField(default='123/123/213', max_length=1024, unique=True),
        ),
        migrations.AddField(
            model_name='studentquestionstatus',
            name='stu_solution',
            field=models.CharField(default='123/123/213', max_length=1024),
        ),
    ]
