# Generated by Django 3.2.13 on 2022-07-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20220704_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbankdesc',
            name='ques_answer',
            field=models.CharField(default='123/123/213', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='questionbankdesc',
            name='ques_sample',
            field=models.CharField(default='123/123/213', max_length=255, unique=True),
        ),
    ]
