# Generated by Django 3.2.13 on 2022-07-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20220704_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbankdesc',
            name='ques_answer',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='questionbankdesc',
            name='ques_sample',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studentquestionstatus',
            name='stu_solution',
            field=models.CharField(max_length=1024),
        ),
    ]
