# Generated by Django 3.2.13 on 2022-07-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_auto_20220704_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbankdesc',
            old_name='ques_Detail',
            new_name='ques_detail',
        ),
    ]
