# Generated by Django 3.2.14 on 2022-07-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_auto_20220707_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbankdesc',
            name='ques_answer',
        ),
        migrations.RemoveField(
            model_name='questionbankdesc',
            name='ques_sample',
        ),
        migrations.AddField(
            model_name='questionbankdesc',
            name='ques_case',
            field=models.CharField(default='/test_case/', max_length=255),
        ),
        migrations.AddField(
            model_name='studentquestionstatus',
            name='language',
            field=models.CharField(default='python3', max_length=64),
        ),
    ]
