# Generated by Django 3.2.14 on 2022-07-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0009_alter_questionbankdesc_ques_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestionstatus',
            name='status',
            field=models.CharField(max_length=64),
        ),
    ]
