# Generated by Django 3.2.14 on 2022-07-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0010_alter_studentquestionstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestionstatus',
            name='status',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
