# Generated by Django 3.2.14 on 2022-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0011_alter_studentquestionstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestionstatus',
            name='memory_limit',
            field=models.CharField(default='102400KB', max_length=1024),
        ),
        migrations.AddField(
            model_name='studentquestionstatus',
            name='time_limit',
            field=models.CharField(default='1000ms', max_length=1024),
        ),
    ]
