# Generated by Django 3.2.14 on 2022-07-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0013_auto_20220710_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbankdesc',
            name='ques_case',
        ),
    ]
