# Generated by Django 3.2.13 on 2022-07-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=12, unique=True)),
                ('stu_img', models.CharField(max_length=1024, null=True)),
                ('stu_pwd', models.CharField(max_length=32)),
                ('stu_name', models.CharField(max_length=10, unique=True)),
                ('stu_gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.classes')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacher')),
            ],
        ),
    ]
